// Code generated by "stringer -type=NodeReportCode"; DO NOT EDIT

package code

import "fmt"

const _NodeReportCode_name = "RcDebugRcPowerOkRcPowerFailRcSocketWr1RcParseFailRcUdpFailRcShNameOkRcLoNameOkRcDmxErrorRcDmxUdpFullRcDmxRxFullRcSwitchErrRcConfigErrRcDmxShortRcFirmwareFailRcUserFailRcFactoryRes"

var _NodeReportCode_index = [...]uint8{0, 7, 16, 27, 38, 49, 58, 68, 78, 88, 100, 111, 122, 133, 143, 157, 167, 179}

func (i NodeReportCode) String() string {
	if i >= NodeReportCode(len(_NodeReportCode_index)-1) {
		return fmt.Sprintf("NodeReportCode(%d)", i)
	}
	return _NodeReportCode_name[_NodeReportCode_index[i]:_NodeReportCode_index[i+1]]
}
