// Code generated by "stringer -type=OpCode"; DO NOT EDIT

package code

import "fmt"

const _OpCode_name = "OpPollOpPollReplyOpDiagDataOpCommandOpOutputOpNzsOpSyncOpAddressOpInputOpTodRequestOpTodDataOpTodControlOpRdmOpRdmSubOpMediaOpMediaPatchOpMediaControlOpMediaContrlReplyOpTimeCodeOpTimeSyncOpTriggerOpDirectoryOpDirectoryReplyOpVideoSetupOpVideoPaletteOpVideoDataOpMacMasterOpMacSlaveOpFirmwareMasterOpFirmwareReplyOpFileTnMasterOpFileFnMasterOpFileFnReplyOpIPProgOpIPProgReply"

var _OpCode_map = map[OpCode]string{
	8192:  _OpCode_name[0:6],
	8448:  _OpCode_name[6:17],
	8960:  _OpCode_name[17:27],
	9216:  _OpCode_name[27:36],
	20480: _OpCode_name[36:44],
	20736: _OpCode_name[44:49],
	20992: _OpCode_name[49:55],
	24576: _OpCode_name[55:64],
	28672: _OpCode_name[64:71],
	32768: _OpCode_name[71:83],
	33024: _OpCode_name[83:92],
	33280: _OpCode_name[92:104],
	33536: _OpCode_name[104:109],
	33792: _OpCode_name[109:117],
	36864: _OpCode_name[117:124],
	37120: _OpCode_name[124:136],
	37376: _OpCode_name[136:150],
	37632: _OpCode_name[150:168],
	38656: _OpCode_name[168:178],
	38912: _OpCode_name[178:188],
	39168: _OpCode_name[188:197],
	39424: _OpCode_name[197:208],
	39680: _OpCode_name[208:224],
	40976: _OpCode_name[224:236],
	40992: _OpCode_name[236:250],
	41024: _OpCode_name[250:261],
	61440: _OpCode_name[261:272],
	61696: _OpCode_name[272:282],
	61952: _OpCode_name[282:298],
	62208: _OpCode_name[298:313],
	62464: _OpCode_name[313:327],
	62720: _OpCode_name[327:341],
	62976: _OpCode_name[341:354],
	63488: _OpCode_name[354:362],
	63744: _OpCode_name[362:375],
}

func (i OpCode) String() string {
	if str, ok := _OpCode_map[i]; ok {
		return str
	}
	return fmt.Sprintf("OpCode(%d)", i)
}
