// Code generated by "stringer -type=OpCode"; DO NOT EDIT

package code

import "fmt"

const _OpCode_name = "OpPollOpPollReplyOpDiagDataOpCommandOpOutputOpNzsOpSyncOpAddressOpInputOpTodRequestOpTodDataOpTodControlOpRdmOpRdmSubOpMediaOpMediaPatchOpMediaControlOpMediaContrlReplyOpTimeCodeOpTimeSyncOpTriggerOpDirectoryOpDirectoryReplyOpMacMasterOpMacSlaveOpFirmwareMasterOpFirmwareReplyOpFileTnMasterOpFileFnMasterOpFileFnReplyOpIPProgOpIPProgReplyOpVideoSetupOpVideoPaletteOpVideoData"

var _OpCode_map = map[OpCode]string{
	32:    _OpCode_name[0:6],
	33:    _OpCode_name[6:17],
	35:    _OpCode_name[17:27],
	36:    _OpCode_name[27:36],
	80:    _OpCode_name[36:44],
	81:    _OpCode_name[44:49],
	82:    _OpCode_name[49:55],
	96:    _OpCode_name[55:64],
	112:   _OpCode_name[64:71],
	128:   _OpCode_name[71:83],
	129:   _OpCode_name[83:92],
	130:   _OpCode_name[92:104],
	131:   _OpCode_name[104:109],
	132:   _OpCode_name[109:117],
	144:   _OpCode_name[117:124],
	145:   _OpCode_name[124:136],
	146:   _OpCode_name[136:150],
	147:   _OpCode_name[150:168],
	151:   _OpCode_name[168:178],
	152:   _OpCode_name[178:188],
	153:   _OpCode_name[188:197],
	154:   _OpCode_name[197:208],
	155:   _OpCode_name[208:224],
	240:   _OpCode_name[224:235],
	241:   _OpCode_name[235:245],
	242:   _OpCode_name[245:261],
	243:   _OpCode_name[261:276],
	244:   _OpCode_name[276:290],
	245:   _OpCode_name[290:304],
	246:   _OpCode_name[304:317],
	248:   _OpCode_name[317:325],
	249:   _OpCode_name[325:338],
	4256:  _OpCode_name[338:350],
	8352:  _OpCode_name[350:364],
	16544: _OpCode_name[364:375],
}

func (i OpCode) String() string {
	if str, ok := _OpCode_map[i]; ok {
		return str
	}
	return fmt.Sprintf("OpCode(%d)", i)
}
