// Code generated by "stringer -type=StyleCode"; DO NOT EDIT

package code

import "fmt"

const _StyleCode_name = "StNodeStControllerStMediaStRouteStBackupStConfigStVisual"

var _StyleCode_index = [...]uint8{0, 6, 18, 25, 32, 40, 48, 56}

func (i StyleCode) String() string {
	if i >= StyleCode(len(_StyleCode_index)-1) {
		return fmt.Sprintf("StyleCode(%d)", i)
	}
	return _StyleCode_name[_StyleCode_index[i]:_StyleCode_index[i+1]]
}
